# Generated by Django 2.1.7 on 2019-06-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('co_id', models.IntegerField(primary_key=True, serialize=False)),
                ('co_name', models.CharField(max_length=50)),
                ('co_pice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co_number', models.IntegerField()),
                ('co_image', models.ImageField(upload_to='')),
                ('co_kind', models.IntegerField()),
                ('co_brief_introduction', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
        migrations.CreateModel(
            name='Commodity_brief_introduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cbi', models.TextField()),
                ('cbi_co', models.IntegerField()),
            ],
            options={
                'db_table': 'commodity_brief_introduction',
            },
        ),
        migrations.CreateModel(
            name='Commodity_img',
            fields=[
                ('ci_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ci_img', models.ImageField(upload_to='')),
                ('ci_co', models.IntegerField()),
            ],
            options={
                'db_table': 'commodity_img',
            },
        ),
        migrations.CreateModel(
            name='Commodity_kind',
            fields=[
                ('ct_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ct_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'commodity_kind',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_image', models.ImageField(upload_to='')),
                ('m_name', models.CharField(max_length=20)),
                ('m_co', models.IntegerField()),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('ro_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_image', models.ImageField(upload_to='')),
                ('ro_co', models.IntegerField()),
            ],
            options={
                'db_table': 'rotation',
            },
        ),
    ]
