# Generated by Django 2.1.7 on 2019-06-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fxhhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fxhh_image', models.ImageField(upload_to='')),
                ('fxhh_pice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'fxhh',
            },
        ),
        migrations.CreateModel(
            name='Hmzjb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmzj_image', models.ImageField(upload_to='')),
                ('hmzj_pice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'hmzj',
            },
        ),
        migrations.CreateModel(
            name='Jdmsb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdms_image', models.ImageField(upload_to='')),
                ('jdms_pice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'jdms',
            },
        ),
        migrations.CreateModel(
            name='Ppmsb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppms_image', models.ImageField(upload_to='')),
                ('ppms_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ppms',
            },
        ),
    ]
