# Generated by Django 2.1.7 on 2019-06-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fxhhb_hmzjb_jdmsb_ppmsb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_user', models.CharField(max_length=20)),
                ('car_co', models.IntegerField()),
                ('car_number', models.IntegerField()),
                ('car_sele', models.IntegerField()),
                ('car_money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Userinf',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('userpassword', models.CharField(max_length=15)),
                ('userphone', models.IntegerField()),
                ('token', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userin',
            },
        ),
        migrations.AlterField(
            model_name='commodity',
            name='co_image',
            field=models.CharField(max_length=50),
        ),
    ]
