# Generated by Django 2.1.7 on 2019-06-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190626_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercar',
            name='car_image',
            field=models.ImageField(default='aaa', upload_to=''),
        ),
        migrations.AddField(
            model_name='usercar',
            name='co_brief_introduction',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
