# Generated by Django 2.1.7 on 2019-06-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190627_1105'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercar',
            table='usecar',
        ),
    ]
