# Generated by Django 2.1.7 on 2019-06-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinform',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('userpassword', models.CharField(max_length=15)),
                ('userphone', models.IntegerField()),
                ('token', models.CharField(max_length=50)),
                ('user_head', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'userinform',
            },
        ),
        migrations.DeleteModel(
            name='Userinf',
        ),
    ]
